@echo off
mode con cp select=437 >nul
setlocal EnableExtensions EnableDelayedExpansion

rem Values are generated by trans.sh when available.
if not defined mac_addr set "mac_addr="
if defined mac_addr (
    set "mac_query=%mac_addr::=-%"
) else (
    set "mac_query="
)
if not defined ipv4_cidr set "ipv4_cidr="
if not defined ipv4_gateway set "ipv4_gateway="
if not defined ipv6_cidr set "ipv6_cidr="
if not defined ipv6_gateway set "ipv6_gateway="

rem Disable IPv6 randomization
netsh interface ipv6 set global randomizeidentifiers=disabled >nul 2>&1

set "id="
set /a retry=15
:retry_find_interface
call :resolve_interface
if defined id goto interface_found
set /a retry-=1
if !retry! LEQ 0 goto interface_not_found
timeout /t 2 /nobreak >nul
goto retry_find_interface

:interface_not_found
echo ERROR: No usable network interface found
goto cleanup

:interface_found
echo Using InterfaceIndex: %id%
call :resolve_interface_name
if not defined ifname set "ifname=%id%"
echo Using InterfaceName: %ifname%

set "ipv4_addr="
set "ipv4_mask="
set "ipv4_prefix="
if defined ipv4_cidr (
    call :parse_cidr "%ipv4_cidr%" ipv4_addr ipv4_prefix
    if defined ipv4_addr if defined ipv4_prefix call :cidr_to_mask !ipv4_prefix! ipv4_mask
)

set "ipv6_addr="
set "ipv6_prefix="
if defined ipv6_cidr (
    call :parse_cidr "%ipv6_cidr%" ipv6_addr ipv6_prefix
)

rem Explicit IPv4 behavior: static if provided, otherwise enforce DHCP.
if defined ipv4_addr if defined ipv4_gateway if defined ipv4_mask (
    echo Applying static IPv4: !ipv4_addr!/!ipv4_prefix! gw !ipv4_gateway!
    netsh interface ipv4 set address name="%ifname%" static !ipv4_addr! !ipv4_mask! !ipv4_gateway! 1 >nul
    call :apply_ipv4_dns
) else (
    echo Enforcing DHCP IPv4
    netsh interface ipv4 set address name="%ifname%" dhcp >nul
    netsh interface ipv4 set dnsservers name="%ifname%" dhcp >nul
)

rem IPv6 behavior: static only when explicitly provided; otherwise keep auto behavior.
if defined ipv6_addr if defined ipv6_gateway if defined ipv6_prefix (
    echo Applying static IPv6: !ipv6_addr!/!ipv6_prefix! gw !ipv6_gateway!
    netsh interface ipv6 add address interface="%ifname%" !ipv6_addr!/!ipv6_prefix! >nul
    netsh interface ipv6 add route ::/0 interface="%ifname%" !ipv6_gateway! >nul
    call :apply_ipv6_dns
) else (
    if defined ipv6_dns1 (
        echo Applying IPv6 DNS override
        call :apply_ipv6_dns
    )
)

echo.
echo Network configuration applied.
goto cleanup

:resolve_interface
set "id="
if defined mac_query call :find_interface_by_mac
if defined id goto :eof
call :find_interface_auto
goto :eof

:resolve_interface_name
set "ifname="
for /f "usebackq delims=" %%a in (`powershell -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command "(Get-NetAdapter -InterfaceIndex %id% -ErrorAction SilentlyContinue | Select-Object -First 1 -ExpandProperty Name)"`) do set "ifname=%%a"
if defined ifname goto :eof
for /f "usebackq delims=" %%a in (`powershell -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command "(Get-WmiObject Win32_NetworkAdapter -ErrorAction SilentlyContinue | Where-Object { $_.InterfaceIndex -eq %id% } | Select-Object -First 1 -ExpandProperty NetConnectionID)"`) do set "ifname=%%a"
goto :eof

:find_interface_by_mac
if exist "%windir%\system32\wbem\wmic.exe" (
    for /f "tokens=2 delims==" %%a in (
        'wmic nic where "MACAddress='%mac_query%'" get InterfaceIndex /format:list ^| findstr "^InterfaceIndex=[0-9][0-9]*$"'
    ) do set "id=%%a"
)
if defined id goto :eof
for /f %%a in ('powershell -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass ^
    -Command "$m='%mac_query%'.ToUpper();(Get-CimInstance Win32_NetworkAdapter -ErrorAction SilentlyContinue | Where-Object { $_.MACAddress -and $_.MACAddress.ToUpper() -eq $m } | Sort-Object InterfaceIndex | Select-Object -First 1 -ExpandProperty InterfaceIndex)" ^| findstr "^[0-9][0-9]*$"') do set "id=%%a"
goto :eof

:find_interface_auto
for /f %%a in ('powershell -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass ^
    -Command "(Get-NetAdapter -ErrorAction SilentlyContinue | Where-Object { $_.HardwareInterface -eq $true -and $_.Name -notmatch ''Loopback|Pseudo|Teredo|isatap'' } | Sort-Object @{Expression={ if($_.Status -eq ''Up''){0}else{1}}}, ifIndex | Select-Object -First 1 -ExpandProperty ifIndex)" ^| findstr "^[0-9][0-9]*$"') do set "id=%%a"
if defined id goto :eof
for /f %%a in ('powershell -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass ^
    -Command "(Get-WmiObject Win32_NetworkAdapter -ErrorAction SilentlyContinue | Where-Object { $_.MACAddress -ne $null -and $_.PhysicalAdapter -eq $true } | Sort-Object @{Expression={ if($_.NetConnectionStatus -eq 2){0}else{1}}}, InterfaceIndex | Select-Object -First 1 -ExpandProperty InterfaceIndex)" ^| findstr "^[0-9][0-9]*$"') do set "id=%%a"
goto :eof

:apply_ipv4_dns
if not defined ipv4_dns1 goto :eof
echo Applying IPv4 DNS override
netsh interface ipv4 set dnsservers name="%ifname%" static %ipv4_dns1% primary >nul
set /a i=2
:loop_ipv4_dns
call set "cur=%%ipv4_dns%i%%%"
if not defined cur goto :eof
netsh interface ipv4 add dnsservers name="%ifname%" !cur! index=!i! >nul
set /a i+=1
goto loop_ipv4_dns

:apply_ipv6_dns
if not defined ipv6_dns1 goto :eof
echo Applying IPv6 DNS override
netsh interface ipv6 set dnsservers interface="%ifname%" static %ipv6_dns1% primary >nul
set /a i=2
:loop_ipv6_dns
call set "cur=%%ipv6_dns%i%%%"
if not defined cur goto :eof
netsh interface ipv6 add dnsservers interface="%ifname%" !cur! index=!i! >nul
set /a i+=1
goto loop_ipv6_dns

:parse_cidr
setlocal EnableDelayedExpansion
set "value=%~1"
set "addr="
set "prefix="
for /f "tokens=1,2 delims=/" %%a in ("%value%") do (
    set "addr=%%a"
    set "prefix=%%b"
)
endlocal & (
    set "%~2=%addr%"
    set "%~3=%prefix%"
)
goto :eof

:cidr_to_mask
setlocal EnableDelayedExpansion
set bits=%1
if not defined bits set bits=0
if !bits! LSS 0 set bits=0
if !bits! GTR 32 set bits=32

set mask=
for %%i in (1 2 3 4) do (
    if !bits! GEQ 8 (
        set /a octet=255
        set /a bits-=8
    ) else (
        if !bits! EQU 0 (
            set /a octet=0
        ) else (
            set /a octet=256 - (1 << (8 - bits))
        )
        set bits=0
    )
    if defined mask (
        set mask=!mask!.!octet!
    ) else (
        set mask=!octet!
    )
)
endlocal & set %2=%mask%
goto :eof

:cleanup
REM Remove memory dump files
del /q /f "C:\Windows\*.DMP" >nul 2>&1
for /d %%D in ("C:\Windows\Minidump") do rd /s /q "%%D"

REM Set account lockout threshold to 0 (disable)
net accounts /lockoutthreshold:0 >nul 2>&1

rem Delete script file after execution
del "%~f0"
